version: '3.8'

services:
  # Apache ve PHP service
  web:
    image: php:8-apache
    container_name: php-apache-container
    ports:
      - "8080:80"
    volumes:
      - ./web:/var/www/html

  # MySQL service
  mysql:
    image: mysql:8.0
    networks:
      - my-network
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rdc
      MYSQL_DATABASE: database1
      MYSQL_USER: ccorbaci
      MYSQL_PASSWORD: P@ssw0rdc
    volumes:
      - ./mysql-data:/var/lib/mysql

  # phpMyAdmin service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    networks:
      - my-network
    container_name: phpmyadmin-container
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: P@ssw0rdc
    depends_on:
      - mysql

# Define networks
networks:
  my-network: